version: '3'
services:
  
  #PHP Service
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: squid-solutions/laravel
    container_name: app-zip-codes
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_ZIP: 1
    volumes:
        - ./:/var/www/zip_codes
        - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
        - squid-solutions

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "1480:80"
      - "14443:443"
    volumes:
    - ./:/var/www/zip_codes
    - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - squid-solutions
    depends_on:
      - mysql

  #MySQL Service
  mysql:
    image: 'mariadb:latest'
    container_name: zipcodes-laravel-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - squid-solutions

#Docker Networks
networks:
  squid-solutions:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local